/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateRunner {
  domain: string
  apiUrl: string
  proxyUrl: string
  apiKey: string
  cpu: number
  memoryGiB: number
  diskGiB: number
  gpu: number
  gpuType: string
  class: CreateRunnerClassEnum
  region: string
  version: string
}

export const CreateRunnerClassEnum = {
  SMALL: 'small',
  MEDIUM: 'medium',
  LARGE: 'large',
} as const

export type CreateRunnerClassEnum = (typeof CreateRunnerClassEnum)[keyof typeof CreateRunnerClassEnum]
