/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Job {
  /**
   * The ID of the job
   */
  id: string
  /**
   * The type of the job
   */
  type: JobTypeEnum
  /**
   * The status of the job
   */
  status: JobStatusEnum
  /**
   * The type of resource this job operates on
   */
  resourceType?: JobResourceTypeEnum
  /**
   * The ID of the resource this job operates on (sandboxId, snapshotRef, etc.)
   */
  resourceId?: string
  /**
   * Job-specific payload data (operational metadata)
   */
  payload?: { [key: string]: any }
  /**
   * OpenTelemetry trace context for distributed tracing (W3C Trace Context format)
   */
  traceContext?: { [key: string]: any }
  /**
   * Error message if the job failed
   */
  errorMessage?: string
  /**
   * The creation timestamp of the job
   */
  createdAt: string
  /**
   * The last update timestamp of the job
   */
  updatedAt?: string
}

export const JobTypeEnum = {
  CREATE_SANDBOX: 'CREATE_SANDBOX',
  START_SANDBOX: 'START_SANDBOX',
  STOP_SANDBOX: 'STOP_SANDBOX',
  DESTROY_SANDBOX: 'DESTROY_SANDBOX',
  CREATE_BACKUP: 'CREATE_BACKUP',
  BUILD_SNAPSHOT: 'BUILD_SNAPSHOT',
  PULL_SNAPSHOT: 'PULL_SNAPSHOT',
  REMOVE_SNAPSHOT: 'REMOVE_SNAPSHOT',
} as const

export type JobTypeEnum = (typeof JobTypeEnum)[keyof typeof JobTypeEnum]
export const JobStatusEnum = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const

export type JobStatusEnum = (typeof JobStatusEnum)[keyof typeof JobStatusEnum]
export const JobResourceTypeEnum = {
  SANDBOX: 'SANDBOX',
  SNAPSHOT: 'SNAPSHOT',
  BACKUP: 'BACKUP',
} as const

export type JobResourceTypeEnum = (typeof JobResourceTypeEnum)[keyof typeof JobResourceTypeEnum]
