/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Organization {
  /**
   * Organization ID
   */
  id: string
  /**
   * Organization name
   */
  name: string
  /**
   * User ID of the organization creator
   */
  createdBy: string
  /**
   * Personal organization flag
   */
  personal: boolean
  /**
   * Creation timestamp
   */
  createdAt: Date
  /**
   * Last update timestamp
   */
  updatedAt: Date
  /**
   * Suspended flag
   */
  suspended: boolean
  /**
   * Suspended at
   */
  suspendedAt: Date
  /**
   * Suspended reason
   */
  suspensionReason: string
  /**
   * Suspended until
   */
  suspendedUntil: Date
  /**
   * Suspension cleanup grace period hours
   */
  suspensionCleanupGracePeriodHours: number
  /**
   * Total CPU quota
   */
  totalCpuQuota: number
  /**
   * Total memory quota
   */
  totalMemoryQuota: number
  /**
   * Total disk quota
   */
  totalDiskQuota: number
  /**
   * Max CPU per sandbox
   */
  maxCpuPerSandbox: number
  /**
   * Max memory per sandbox
   */
  maxMemoryPerSandbox: number
  /**
   * Max disk per sandbox
   */
  maxDiskPerSandbox: number
  /**
   * Sandbox default network block all
   */
  sandboxLimitedNetworkEgress: boolean
  /**
   * Default region
   * @type {string}
   * @memberof Organization
   */
  defaultRegion: string
}
