/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Region {
  /**
   * Region ID
   */
  id: string
  /**
   * Region name
   */
  name: string
  /**
   * Organization ID
   */
  organizationId: string | null
  /**
   * Creation timestamp
   */
  createdAt: string
  /**
   * Last update timestamp
   */
  updatedAt: string
}
