/* tslint:disable */

/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateJobStatus {
  /**
   * The new status of the job
   */
  status: UpdateJobStatusStatusEnum
  /**
   * Error message if the job failed
   */
  errorMessage?: string
}

export const UpdateJobStatusStatusEnum = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const

export type UpdateJobStatusStatusEnum = (typeof UpdateJobStatusStatusEnum)[keyof typeof UpdateJobStatusStatusEnum]
