/* tslint:disable */

/**
 * Daytona Daemon API
 * Daytona Daemon API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ExecuteRequest {
  command: string
  /**
   * Current working directory
   */
  cwd?: string
  /**
   * Timeout in seconds, defaults to 10 seconds
   */
  timeout?: number
}
